global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pvz-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']